name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php-versions }}
    strategy:
      matrix:
        php-versions:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: Check code style
        run: php vendor/bin/phpcs --standard=PSR12 --extensions=php src
      - name: Run unit tests
        run: php vendor/bin/codecept run --coverage --coverage-xml
